# todo localizations-1 3: create file l10.yaml and add configuration
arb-dir: lib/l10n
template-arb-file: app_id.arb
output-localization-file: app_localizations.dart
# todo localizations-1 4: create folder lib/l10n and add catalog files