name: dicoding_subscriptions
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # todo localizations-1 1: add library
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  # todo localizations-1 15: add library for open setting
  app_settings: ^4.1.1
  # todo localizations-2 1: add library for manage state
  provider: 6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  # todo localizations-1 2: add generate flag
  generate: true
  uses-material-design: true
  assets:
    - assets/dicoding-academy.png